(() => {
  const A = (src, alt, caption = '', kind = 'image') => ({ src, alt, caption, kind });
  const extra = (folder, prefix, label, count = 4) => Array.from({ length: count }, (_, i) => A(`assets/${folder}/${prefix}-${String(i + 1).padStart(2, '0')}.avif`, `${label} ${i + 1}`));
  const G = {
    icogam: ['ICOGAM', [A('assets/collections/icogam-current-01.jpg','Feed del Colegio de Gestores Administrativos de Madrid'),...Array.from({length:9},(_,i)=>A(`assets/collections/icogam-current-${String(i+2).padStart(2,'0')}.jpg`,`Pieza de ICOGAM ${i+1}`))]],
    parques: ['Parques de Chile', [A('assets/collections/parques-feed.avif','Feed de Parques de Chile'),A('assets/collections/parques-ad-1.avif','Anuncio de Parques de Chile'),A('assets/collections/parques-ad-2.avif','Pieza territorial de Parques de Chile'),...extra('extra','parques','Pieza de Parques de Chile')]],
    protools: ['Protools Chile', [A('assets/collections/protools-feed.avif','Feed de Protools Chile'),A('assets/collections/protools-post-1.avif','Post de Protools Chile'),A('assets/collections/protools-post-2.avif','Post de Protools Chile'),A('assets/collections/protools-post-3.avif','Post de Protools Chile'),...extra('extra','protools','Pieza de Protools Chile')]],
    copa: ['Copa Parcelas', [A('assets/projects/copa-post.avif','Post de Copa Parcelas'),A('assets/projects/copa-parcela.avif','Pieza de Copa Parcelas'),...extra('extra','copa','Pieza de Copa Parcelas')]],
    casona: ['Casona F.C.', [A('assets/projects/casona-feed-new.jpg','Feed de Casona F.C.'),A('assets/projects/casona-flyer.avif','Pieza de Casona F.C.'),...extra('extra','casona','Pieza de Casona F.C.')]],
    lechuga: ['La Lechuga Express', [A('assets/collections/lechuga-feed.avif','Feed de La Lechuga Express'),A('assets/collections/lechuga-post-1.avif','Post de La Lechuga Express'),A('assets/collections/lechuga-post-2.avif','Post de La Lechuga Express'),A('assets/collections/lechuga-post-3.avif','Post de La Lechuga Express'),...extra('extra','lechuga','Pieza de La Lechuga Express')]],
    sigue: ['Sigue Seguro', [A('assets/projects/sigue-seguro-proteccion.avif','Post de Sigue Seguro'),A('assets/projects/sigue-seguro-automotriz.avif','Post de Sigue Seguro'),...extra('extra','sigue','Pieza de Sigue Seguro')]],
    conquista: ['Conquista tu Parcela', [A('assets/projects/conquista-feed.avif','Feed de Conquista tu Parcela'),...extra('extra','conquista','Pieza de Conquista tu Parcela')]],
    carita: ['Carita de Muñeca', [A('assets/projects/carita-feed.avif','Feed de Carita de Muñeca'),...extra('extra','carita','Pieza de Carita de Muñeca')]],
    logos: ['Diseño de logos', [A('assets/logos/casona-fc.avif','Logotipo de Casona F.C.'),A('assets/logos/copa-parcelas.avif','Logotipo de Copa Parcelas'),A('assets/logos/rupaca.avif','Logotipo de Inversiones Rupaca LLC'),A('assets/logos/wi-agencia.avif','Logotipo de WI Agencia'),...Array.from({length:9},(_,i)=>A(`assets/extra/graphic-${String(i+1).padStart(2,'0')}.avif`,`Logotipo adicional ${i+1}`))]],
    flyers: ['Diseño de flyers', [A('assets/collections/flyer-enrique.avif','Flyer de Enrique Martínez'),A('assets/collections/flyer-santa-tere.avif','Flyer de Santa Teresa'),A('assets/collections/flyer-casona.avif','Flyer de Casona F.C.'),A('assets/collections/flyer-lechuga.avif','Flyer de La Lechuga Express'),...Array.from({length:5},(_,i)=>A(`assets/extra/graphic-${String(i+10).padStart(2,'0')}.avif`,`Flyer adicional ${i+1}`))]],
    web: ['Diseño web', [A('assets/collections/web-aristek.avif','Preview web de Aristek'),A('assets/collections/web-casona.avif','Preview web de Casona F.C.'),A('assets/collections/web-viajes.avif','Preview web de Viajes La Mareta'),A('assets/collections/web-julie.avif','Preview web de Julie Abreu'),A('assets/collections/web-copa.avif','Preview web de Copa Parcelas'),A('assets/collections/web-septiembre.avif','Preview web de Septiembre 21')]],
    youtube: ['Miniaturas de YouTube', [A('assets/graphic/youtube-01.jpg','Miniatura de YouTube 1'),A('assets/graphic/youtube-02.jpg','Miniatura de YouTube 2'),A('assets/graphic/youtube-03.jpg','Miniatura de YouTube 3'),A('assets/graphic/youtube-04.jpg','Miniatura de YouTube 4'),A('assets/graphic/youtube-05.jpg','Miniatura de YouTube 5'),A('assets/graphic/youtube-06.jpg','Miniatura de YouTube 6')]],
    otros: ['Otros diseños', [A('assets/graphic/otros-cover.jpg','Portada de otros diseños','Portada de otros diseños'),...Array.from({length:24},(_,i)=>A(`assets/graphic/otros-current-${String(i+1).padStart(2,'0')}.jpg`,`Otro diseño ${i+1}`,`Otro diseño ${i+1}`)),...Array.from({length:7},(_,i)=>A(`assets/graphic/hacienda-el-quillay-${i+1}.jpg`,`Hacienda El Quillay, página ${i+1}`,`Hacienda El Quillay · página ${i+1}`))]],
    fotos: ['Fotos de eventos', Array.from({length:6},(_,i)=>A(`assets/media/event-current-${String(i+1).padStart(2,'0')}.jpg`,`Fotografía de evento ${i+1}`,`Foto de evento ${i+1}`))],
    cocinero: ['Cocinero profesional', [A('assets/certificates/cocinero-profesional.avif','Certificado de cocinero profesional')]], panaderia: ['Panadería y repostería', [A('assets/certificates/panaderia-reposteria.avif','Certificado de panadería y repostería')]], emocional: ['Inteligencia emocional', [A('assets/certificates/inteligencia-emocional.avif','Certificado de inteligencia emocional')]], photoshop: ['Katrin Eismann / Photoshop', [A('assets/certificates/katrin-eismann-photoshop.avif','Certificado de Katrin Eismann sobre Photoshop')]], marketing: ['Marketing online', [A('assets/certificates/marketing-online.avif','Certificado de marketing online')]], diplomado: ['Diplomado Marketing y SEO', [A('assets/certificates/diplomado-marketing-seo.avif','Diplomado de marketing digital y SEO')]], ingles: ['Inglés profesional', [A('assets/certificates/ingles-profesional-1.avif','Inglés profesional, página 1'),A('assets/certificates/ingles-profesional-2.avif','Inglés profesional, página 2'),A('assets/certificates/ingles-profesional-3.avif','Inglés profesional, página 3')]], reconocimiento: ['Reconocimiento de cocinero', [A('assets/certificates/reconocimiento-cocinero.avif','Reconocimiento de cocinero profesional')]], titulo: ['Título universitario', [A('assets/certificates/titulo-universitario.avif','Título de Licenciado en Comunicación Social')]]
  };
  const otrosNames = ["portada otros diseños.png","QR Code Poster casona fc .png","certificados_ enrique martinez academypng.png","cupon 2 10% casona fc .png","cupones 10% casona fc .png","diseño 2 tarjeta navidad icogam .png","diseño carpetacopa parcelas  .png","diseño de correo para mailjet .png","diseño de credenciales parques de chile.png","diseño de qr casona fc .png","diseño de tarjeta de navidad 2025 icogam.png","elementos de papeleriap copa parcelas.png","etiquetas de bautizo.png","letreros o fachada de protools local .png","maquetacion revista icogam .png","maquetacion revista icogam cierre .png","maquetacion revista icogam pag extra.png","maquetacion revista icogam1.png","menu casona fc version 1.png","menu casona fc version 2 .png","pdf corporativo copa parcelas .png","portada facebook casona fc.png","portada facebook sigue seguros .png","portada fb copa parcelas.png","tarjeta de presentacion protools 2026.png"]; G.otros[1].forEach((item,i)=>{item.caption=otrosNames[i] || item.caption || `Otro diseño ${i+1}`;});
  const dialog = document.querySelector('#gallery-dialog'), title = document.querySelector('#dialog-title'), main = document.querySelector('#dialog-image'), caption = document.querySelector('#dialog-caption'), thumbs = document.querySelector('#dialog-thumbs'), close = document.querySelector('.dialog-close'); let opener;
  function select(items, index) { const item = items[index]; main.src = item.src; main.alt = item.alt; caption.textContent = item.caption || ''; caption.hidden = !item.caption; [...thumbs.children].forEach((b, i) => b.setAttribute('aria-current', String(i === index))); }
  function openGallery(key, source) { const [name, items] = G[key] || []; if (!items?.length) return; opener = source; title.textContent = name; thumbs.replaceChildren(); items.forEach((item, index) => { const b = document.createElement('button'); const img = document.createElement('img'); b.type = 'button'; b.setAttribute('aria-label', `Ver ${item.alt}`); b.setAttribute('aria-current', String(index === 0)); img.src = item.src; img.alt = ''; img.loading = 'lazy'; b.append(img); b.addEventListener('click', () => select(items, index)); thumbs.append(b); }); select(items, 0); dialog.showModal(); close.focus(); }
  function shut() { if (dialog.open) dialog.close(); }
  document.querySelectorAll('[data-gallery]').forEach(b => { b.setAttribute('aria-haspopup', 'dialog'); b.setAttribute('aria-label', `Abrir galería de ${b.querySelector('span')?.textContent || 'certificación'}`); b.addEventListener('click', () => openGallery(b.dataset.gallery, b)); });
  close.addEventListener('click', shut); dialog.addEventListener('click', e => { if (e.target === dialog) shut(); }); dialog.addEventListener('close', () => { main.removeAttribute('src'); thumbs.replaceChildren(); opener?.focus(); });
  document.querySelectorAll('[data-filter]').forEach(b => b.addEventListener('click', () => { document.querySelectorAll('[data-filter]').forEach(x => x.setAttribute('aria-pressed', String(x === b))); document.querySelectorAll('.collection').forEach(x => { x.hidden = x.dataset.category !== b.dataset.filter; }); shut(); b.focus(); })); document.querySelectorAll('.collection').forEach(x => { x.hidden = x.dataset.category !== 'social'; });
  document.querySelectorAll('.skills article').forEach(card => { const p = card.querySelector('p'); if (p && !p.querySelector('span')) { p.innerHTML = p.textContent.split('·').map(label => `<span>${label.trim()}</span>`).join(''); } card.tabIndex = 0; card.addEventListener('click', () => card.classList.toggle('is-active')); });
  const toggle = document.querySelector('.nav-toggle'), links = document.querySelector('.nav-links'); toggle?.addEventListener('click', () => { const isOpen = toggle.getAttribute('aria-expanded') === 'true'; toggle.setAttribute('aria-expanded', String(!isOpen)); links.classList.toggle('is-open', !isOpen); }); links?.querySelectorAll('a').forEach(a => a.addEventListener('click', () => { toggle?.setAttribute('aria-expanded','false'); links.classList.remove('is-open'); }));
})();
